#!/usr/bin/env python3
"""Append comment waves + refresh debriefs for Y11S2 Jun 24 bulk update."""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
UPDATED = "Jun 24, 2026 · morning PT"

WAVES = {
    "rogue_amputee": {
        "debrief": "<p><b>Bronze II · 1,855 RP · 17–20 · 45.9% win rate · 1.01 K/D.</b> Jun 21 was the comeback block — three Calypso/Coastline wins for plus fifty-three RP including a 4K that still lost on Oregon. Jun 22 Chalet 0:4 donated twenty-three back. Main account is live again while the alt sits Silver IV.</p><p><b>Mute at 44.6% over fifty-six defensive rounds</b> still leads volume; <b>Jackal at 63.6% over eleven attack rounds</b> at 3.00 K/D is the Jun 21 heater. <b>Kaid at 63.2% over nineteen</b> keeps the anchor receipt printing.</p><p>Peak <b>1,907</b> this stretch. Forty-five RP to Bronze I. Stack Kaid with Mute, ride Jackal when the footprint needs to close, and stop letting Chalet 0:4s undo Calypso Ws.</p>",
        "comments": [
            {"type": "map", "subject": "Chalet", "date": "Jun 22", "text": "Jun 22 Chalet 0:4 — two-four-one at one hundred percent headshots, Victim and a 2K buried in a shutout. Jun 21 banked three wins on Calypso and Coastline; Chalet was the cold open that erased the momentum. Modern Chalet punishes untimed vertical peeks — you had the tags, not the round closure. Bronze I is still forty-five RP away; don't queue tilt after a 0:4 donation."},
            {"type": "operator", "subject": "Mute", "date": "Jun 22", "text": "Fifty-six defensive rounds, 44.6% win rate, 0.77 K/D, fourteen assists — still the volume leader and still treading water. Jammers on the breach wall the attack actually needs, drone denial in prep, overlap with Kaid so Thatcher spends twice. Sub-fifty on fifty-six rounds is placement discipline, not aim — fix the wall before you fix the gun."},
            {"type": "operator", "subject": "Jackal", "date": "Jun 21", "text": "Eleven attack rounds, 63.6% win rate, 3.00 K/D, sixty percent headshots — the Jun 21 Calypso heater in one row. Footprint tracking through walls plus refrags off the ping is the attack engine when entries sync; seven wins in eleven says queue him when the stack commits to trades, not solo hero peeks."},
            {"type": "operator", "subject": "Nomad", "date": "Jun 21", "text": "Thirty-six attack rounds, 50.0% win rate, 1.22 K/D, ten assists — still the disciplined line beside Dokkaebi. Airjabs seal the flank the roamers use to collapse your execute; eighteen wins in thirty-six is break-even volume done right. Jun 21 Oregon L had impact tags — Nomad's job is map control first, highlight ball second."},
            {"type": "operator", "subject": "Dokkaebi", "date": "Jun 21", "text": "Twenty-six attack rounds, 46.2% win rate, 1.06 K/D, twelve assists — Jegeo Payload still converting at volume. Scan, hack, force phone discipline, collect the refrag; twelve assists on eighteen kills says the remaster is team work. Stay parked beside Nomad — Gridlock at 22.2% isn't competing for this slot."},
            {"type": "operator", "subject": "Kaid", "date": "Jun 21", "text": "Nineteen defensive rounds, 63.2% win rate, even K/D, five assists — the claws still print when Mute treads water. Electroclaws on the breach wall and hatch that gate the hard push; twelve wins in nineteen says the anchor habit holds. Stack with Mute on Calypso nights so denial actually sticks."},
        ],
    },
    "lcew4ll0wcome": {
        "debrief": "<p><b>Silver IV · 2,182 RP · 11–16 · 48.1% win rate · 1.20 K/D.</b> Jun 20 squad night banked Fortress through Border; Jun 21 Outback 5:4 with a 1v3 Clutch and two 2K tags parked the alt at Silver IV. Twenty-three RP peeled off the 2,191 peak but the smurf is climbing again.</p><p><b>Kaid at 82.4% over seventeen defensive rounds</b> at 4.00 K/D is absurd anchor math. <b>Valkyrie at 68.8% over sixteen</b> and <b>Kapkan at 70.0% over ten</b> back the denial row. Jackal still leads attack volume at thirty rounds.</p><p>Peak <b>2,191</b>. Eighteen RP to Silver III. Queue Kaid and Valkyrie on defense, stop spreading Gridlock at 0% — and treat the alt like a rank push, not a highlight reel audition.</p>",
        "comments": [
            {"type": "map", "subject": "Outback", "date": "Jun 21", "text": "Jun 21 Outback 5:4 — six-six-two, fifty percent headshots, a 1v3 Clutch and two 2K tags on the W that reclaimed twenty-seven RP. After Jun 20's squad marathon and a 0:4 Outback tax the same night, this was the alt's closure read: trades that finish the set, not decorations on another L. Silver IV at 2,182 — eighteen RP from Silver III."},
            {"type": "operator", "subject": "Kaid", "date": "Jun 21", "text": "Seventeen defensive rounds, 82.4% win rate, 4.00 K/D, seven assists — the smurf's anchor receipt. Electroclaws on the wall that gates the real push; fourteen wins in seventeen says denial over highlight frags. This is the template Rogue's main dossier keeps chasing — protect these minutes, don't dilute with Nomad spread on defense."},
            {"type": "operator", "subject": "Valkyrie", "date": "Jun 21", "text": "Sixteen defensive rounds, 68.8% win rate, 1.86 K/D, five assists — Black Eye intel buying trades the sheet loves. Eleven wins in sixteen says the alt's defensive ceiling still lives here. Cam coverage on flanks, active callouts, MPX refrags — queue her first on stack defense nights."},
            {"type": "operator", "subject": "Jackal", "date": "Jun 21", "text": "Thirty attack rounds, 36.7% win rate, 1.05 K/D, 54.5% headshots — highest volume on the alt and still below break-even. Footprint tracking works when the execute follows; eleven wins in thirty says the gun is fine, the plant clock isn't. Coach the habit: ping, trade, plant — not ping, peek, donate."},
            {"type": "operator", "subject": "Kapkan", "date": "Jun 21", "text": "Ten defensive rounds, 70.0% win rate, 1.60 K/D, eight assists — trap anchor printing on a tiny sample. Traps on the approach attackers actually walk; seven wins in ten says the placement habit is there. Flex behind Kaid when the site needs denial, not Jackal volume on the other side."},
            {"type": "operator", "subject": "Nomad", "date": "Jun 21", "text": "Twenty-four attack rounds, 33.3% win rate, 0.78 K/D — Airjabs without round closure is the tax. Eight wins in twenty-four says the flex isn't earning queue time over Jackal when Kaid is posting 82.4% on defense. Nomad wins when traps slow the push the team punishes — not solo flank hero ball on a smurf still grinding Silver."},
        ],
    },
    "matticus_hq": {
        "debrief": "<p><b>Silver IV · 2,181 RP · 9–7 · 56.2% win rate · 0.85 K/D.</b> Jun 20 squad night finally hit the ledger — Fortress 5:4 with three 2K tags, Clubhouse 4:0. Jun 21 split Outback 0:4 and Clubhouse 2:0. Rank recovered past the Jun 18 freeze.</p><p><b>Skopós at 69.6% over twenty-three defensive rounds</b> anchors the cam shell; <b>Finka at 66.7% over twelve attack rounds</b> at 1.50 K/D backs the boost. <b>Alibi at 75.0% over twelve</b> is the intel roamer receipt.</p><p>Peak <b>2,181</b> — new season high. Nineteen RP to Silver III. Queue Skopós and Finka, trim the one-round experiments, and keep logging stack nights before the data drifts again.</p>",
        "comments": [
            {"type": "map", "subject": "Fortress", "date": "Jun 20", "text": "Jun 20 Fortress 5:4 — seven-five-three, fifty-seven percent headshots, three 2K tags and a 1v1 Lost on the W that banked twenty-six RP. First squad night on the ledger since Jun 18 — multi-kill impact that actually closed the set instead of decorating another donation. Fortress rewards timed plants and refrags; you brought both after the Calypso tax week."},
            {"type": "operator", "subject": "Skopós", "date": "Jun 20", "text": "Twenty-three defensive rounds, 69.6% win rate, 0.56 K/D, five assists — cam anchor doing the job Y11S2 Dokkaebi remaster punishes if you ignore phone discipline. Sixteen wins in twenty-three says the shell holds; weak K/D is expected on intel anchors when breaches get denied. Dismiss the hack, reposition the cams, let the team trade off your pings."},
            {"type": "operator", "subject": "Finka", "date": "Jun 20", "text": "Twelve attack rounds, 66.7% win rate, 1.50 K/D, sixty-seven percent headshots — the boost operator printing when the stack commits. Eight wins in twelve says timed pushes, not ego peeks; three assists on nine kills says the team ate the advantage. Queue her on execute nights when the plant needs horsepower."},
            {"type": "operator", "subject": "Alibi", "date": "Jun 20", "text": "Twelve defensive rounds, 75.0% win rate, 1.00 K/D, two assists — Prisma decoys on real entry lines, nine wins in twelve. Intel roamer value shows in pings that become trades, not in highlight K/D. Spread decoys on approaches attackers shoot, then MPX refrags off the reveal."},
            {"type": "operator", "subject": "Sens", "date": "Jun 20", "text": "Nine attack rounds, 55.6% win rate, 1.20 K/D, five assists — XK23 era flex with smoke and plant utility. Five wins in nine is a real sample for a secondary pick; coach the habit: smoke the right choke, plant behind cover, don't dry peek because the gun feels good."},
            {"type": "operator", "subject": "Deimos", "date": "Jun 20", "text": "Seven rounds, 57.1% win rate, 1.33 K/D — small volume, positive signal on the Y11S2 attacker flex. Frag-leaning op where K/D matters; four wins in seven says the duels landed when queued intentionally. Don't spread into one-round Ram and Pulse labs while Skopós and Finka carry the real minutes."},
        ],
    },
    "cunderthock": {
        "debrief": "<p><b>Gold V · 2,548 RP · 22–19 · 53.7% win rate · 0.95 K/D.</b> Jun 23 Bank 5:3 closed the week with twenty-seven RP — Gold V secured. Jun 21 was a seven-game marathon: four W three L. Jun 22 Chalet 0:4 with a 4K that still couldn't close was the tax.</p><p><b>Tachanka at 63.1% over one hundred eleven defensive rounds</b> is still the Lord's dossier. <b>Zero at 45.3% over ninety-five attack rounds</b> is the volume bleed to coach.</p><p>Peak <b>2,626</b>. Fifty-two RP to Gold IV. Queue the Lord first, run Zero for cams — not hero peeks — and stop letting Chalet overtime eat rank after Bank already proved the read.</p>",
        "comments": [
            {"type": "map", "subject": "Bank", "date": "Jun 23", "text": "Jun 23 Bank 5:3 — five-six-two, eighty percent headshots, a 2K and a 1v2 Lost on the W that parked you at Gold V. After Jun 22 Chalet donated twenty-six and Jun 21's seven-game block, Bank was the stack-closure read: trades that finish, plant timed, rank secured at 2,548. Fifty-two RP to Gold IV from here."},
            {"type": "operator", "subject": "Tachanka", "date": "Jun 23", "text": "One hundred eleven defensive rounds, 63.1% win rate, 0.93 K/D, thirty-seven assists — the Lord is still the spine of a Gold V dossier. Seventy wins in one-eleven says LMG denial scales when you commit; Jun 22's 4K on a 0:4 Chalet L proves frags without closure still tax rank. Anchor first, refrag second, hero ball never."},
            {"type": "operator", "subject": "Zero", "date": "Jun 21", "text": "Ninety-five attack rounds, 45.3% win rate, 0.85 K/D, twenty-one assists — intel volume without enough round closure. Forty-three wins in ninety-five says the cams are working; the execute isn't always following. Coach the habit: Argus on the breach that opens site, refrag with the team — not solo peek because the K/D looks fine on paper."},
            {"type": "operator", "subject": "Jackal", "date": "Jun 21", "text": "Seven attack rounds, 42.9% win rate, 2.75 K/D, 63.6% headshots — tiny sample, loud frag signal. Footprint tracking when the stack syncs; three wins in seven says don't default over Zero volume, but ride him when the map needs hard trades."},
            {"type": "operator", "subject": "Twitch", "date": "Jun 21", "text": "Six attack rounds, 66.7% win rate, 5.00 K/D — F2 lab that actually closed. Four wins in six says purposeful duelist minutes, not spread disease. Flex behind Tachanka defense when the site needs hard breach denial clear."},
            {"type": "operator", "subject": "Mozzie", "date": "Jun 21", "text": "Two defensive rounds, 100.0% win rate — Y11S2 pest range buff in a micro sample. Both wins says when you queue Mozzie, the pests land on the drone lane that matters. Not a main over the Lord — a surgical deny call on drone-heavy maps."},
        ],
    },
    "grandmaster_sandman": {
        "debrief": "<p><b>Gold V · 2,534 RP · 27–21 · 52.1% win rate · 1.18 K/D.</b> Jun 20 squad block: five wins in seven including Clubhouse 4:0 and Calypso 4:1 with a 4K. Oregon from the prior session still anchors the climb. Sixty-six RP to Gold IV.</p><p><b>Sledge at 52.5% over sixty-one attack rounds</b> at 1.29 K/D leads the hammer. <b>Kaid at 67.9% over twenty-eight defensive rounds</b> and <b>Frost at 70.8% over twenty-four</b> hold the anchor row. <b>Denari at 100% over eleven</b> is the perfect micro sample.</p><p>Peak <b>2,677</b>. Queue Kaid, Frost, and Sledge — not another Calypso marathon that prints highlights and donates the ticket.</p>",
        "comments": [
            {"type": "map", "subject": "Clubhouse", "date": "Jun 20", "text": "Jun 20 Clubhouse 4:0 — four-one-one, fifty percent headshots, a 2K on the shutdown that banked twenty-six RP at 2,534. Squad night symmetry with the stack: clean closure after Bank and Consulate taxes in the same block. Clubhouse rewards stack trades on site — you brought the hammer timing the plant needed."},
            {"type": "operator", "subject": "Sledge", "date": "Jun 20", "text": "Sixty-one attack rounds, 52.5% win rate, 1.29 K/D, nineteen assists — the hammer still leads volume at Gold V. Thirty-two wins in sixty-one says purposeful entries, not nostalgia rushes; 31.7% headshots on sixty-three kills says aim is there when timing is. Queue him when the breach wall is soft and the plant needs space."},
            {"type": "operator", "subject": "Kaid", "date": "Jun 20", "text": "Twenty-eight defensive rounds, 67.9% win rate, 1.22 K/D — Electroclaw anchor printing beside Frost. Nineteen wins in twenty-eight says denial over highlight frags; seven assists on twenty-two kills says the claws bought trades. Stack with Mute on stack nights when the breach actually matters."},
            {"type": "operator", "subject": "Frost", "date": "Jun 20", "text": "Twenty-four defensive rounds, 70.8% win rate, 1.12 K/D, ten assists — trap mat anchor at elite WR. Seventeen wins in twenty-four says welcome mats on the approach attackers walk, not decorative corners. Pair with Kaid on denial sites — the squad's defensive gold standard."},
            {"type": "operator", "subject": "Denari", "date": "Jun 20", "text": "Eleven defensive rounds, 100.0% win rate, 2.50 K/D — perfect sample, loud signal. Eleven wins in eleven says when you queue the Y11S2 defender, the gadget lands. Surgical call, not spread — protect these minutes."},
            {"type": "operator", "subject": "Thorn", "date": "Jun 20", "text": "Nineteen defensive rounds, 47.4% win rate, 1.57 K/D — trap anchor with frag upside below Frost's line. Twenty-two kills on fourteen deaths says the Razorblooms punish when placed on the plant window; sub-fifty WR says placement discipline still needs tuning. Bloom the real approach, hold the angle that collects."},
        ],
    },
    "slackandlack": {
        "debrief": "<p><b>Silver II · 2,349 RP · 24–20 · 54.5% win rate · 1.22 K/D.</b> Jun 21 was a seven-game heater — Coastline 5:3 with fourteen kills and a 4K, Clubhouse 4:0 with three 2K tags. Jun 22 Chalet and Outback shutouts donated fifty-one RP. Jun 20 squad night banked five in seven.</p><p><b>Doc at 58.5% over forty-one defensive rounds</b> at 1.24 K/D anchors. <b>Aruni at 67.6% over thirty-four</b> at 1.92 K/D is the EBR receipt. <b>Osa at 41.7% over thirty-six attack rounds</b> leads attack volume.</p><p>Peak <b>2,377</b>. Fifty-one RP to Silver I. Ride Aruni and Doc, time Osa pushes with the stack, and stop donating back-to-back 0:4s after a fourteen-kill Coastline W.</p>",
        "comments": [
            {"type": "map", "subject": "Coastline", "date": "Jun 21", "text": "Jun 21 Coastline 5:3 — fourteen-seven-one, thirty-five point seven percent headshots, a 4K and 1v1 Clutch on the W that banked twenty-five RP. The Jun 21 marathon's loudest receipt: frag volume that actually closed the set. Coastline punishes teams that win duels but lose the plant — you finished this one."},
            {"type": "operator", "subject": "Aruni", "date": "Jun 21", "text": "Thirty-four defensive rounds, 67.6% win rate, 1.92 K/D, two aces — Surya Gate anchor with real EBR frag upside. Fifty kills on twenty-six deaths says aggressive angle holding is working; twenty-three wins in thirty-four says gates on the entries attackers must cross. Queue her when the site needs denial and duels."},
            {"type": "operator", "subject": "Doc", "date": "Jun 21", "text": "Forty-one defensive rounds, 58.5% win rate, 1.24 K/D, fifty-nine point five percent headshots — MP7 anchor with stim sustain. Forty-two kills on thirty-four deaths, twenty-four wins in forty-one — highest defensive volume and above break-even. Hold the site angle, stim the trade, don't ego peek off the anchor role."},
            {"type": "operator", "subject": "Osa", "date": "Jun 21", "text": "Thirty-six attack rounds, 41.7% win rate, 1.33 K/D, fifty-seven point five percent headshots — T-5 shield and plant pressure at volume. Fifteen wins in thirty-six says the attack spread needs closure discipline; one ace says the ceiling is there when pushes sync. Coach the habit: shield the planter, not the solo peek."},
            {"type": "operator", "subject": "Thermite", "date": "Jun 21", "text": "Twenty-two attack rounds, 45.5% win rate, 1.18 K/D — hard breach flex when the wall matters. Ten wins in twenty-two says situational value over default; pair with Thatcher clear on ranked breach walls. Not every site needs Thermite — queue when the reinforced wall is the win condition."},
            {"type": "operator", "subject": "Bandit", "date": "Jun 21", "text": "Six defensive rounds, 66.7% win rate, 5.00 K/D — MP7 trick anchor in a tiny sample. Four wins in six says active tricking when queued intentionally. Flex behind Doc and Aruni volume — not a spread pick over the denial chairs that actually print."},
        ],
    },
    "mjester1337": {
        "debrief": "<p><b>Bronze III · 1,700 RP · 59–52 · 53.2% win rate · 0.84 K/D.</b> Jun 20 squad marathon plus solo queue pushed one hundred eleven matches. Jun 21 four-win streak; Jun 23 Calypso split left you at 1,700 — eleven RP from Bronze II on the old peak, now grinding new ground at 1,724 session high.</p><p><b>Thorn at 60.8% over one hundred fifty-three defensive rounds</b> is the season spine. <b>Denari at 51.5% over one hundred one</b> and <b>Dokkaebi at 45.6% over sixty-eight</b> split attack duty.</p><p>Peak <b>1,724</b> this stretch. One hundred RP to Bronze II. Queue Thorn, stop the Jun 23 Outback 0:4 Victim donations, and let the trap anchor carry what the K/D sheet can't.</p>",
        "comments": [
            {"type": "map", "subject": "Calypso Casino", "date": "Jun 23", "text": "Jun 23 Calypso split — 4:2 W with eight-two-two and twin 3K tags, then 4:5 L with Victim and two 2K tags buried in a loss. Vertical casino punishes untimed pushes; you proved both outcomes in one session. Bronze III at 1,700 — closure on the second game decides whether the night prints or donates."},
            {"type": "operator", "subject": "Thorn", "date": "Jun 23", "text": "One hundred fifty-three defensive rounds, 60.8% win rate, 1.21 K/D, sixty-three assists — the season's spine at one hundred eleven matches. Ninety-three wins in one-fifty-three says Razorblooms on the plant window or choke the attack walks; K/D undersells trap value, but 1.21 says you're collecting too. Queue her first on defense — not another Montagne spread night."},
            {"type": "operator", "subject": "Denari", "date": "Jun 23", "text": "One hundred one defensive rounds, 51.5% win rate, 0.55 K/D, sixty-eight point nine percent headshots — Y11S2 defender at volume with team impact over frags. Fifty-two wins in one-oh-one says the gadget is doing work even when K/D looks thin; thirty-four assists on forty-five kills says round impact. Anchor-trap op — judge denial and assists, not highlight K/D."},
            {"type": "operator", "subject": "Dokkaebi", "date": "Jun 23", "text": "Sixty-eight attack rounds, 45.6% win rate, 0.88 K/D, twenty-four assists — Jegeo Payload at grind volume. Thirty-one wins in sixty-eight says the hack converts when the stack syncs; twenty-four assists says phone pressure is team value. Stay on her for attack defaults over Gridlock at fifty percent with weaker K/D."},
            {"type": "operator", "subject": "Thatcher", "date": "Jun 22", "text": "Thirteen attack rounds, 76.9% win rate, 1.80 K/D — EMP support printing in a small sample. Ten wins in thirteen says breach prep when the wall matters; zero assists still fine for Thatcher's job — deny Bandit/Mute, let the breach stick. Surgical pick on hard-wall sites."},
            {"type": "operator", "subject": "Maestro", "date": "Jun 21", "text": "Seven defensive rounds, 85.7% win rate, 1.00 K/D, seven assists — cam anchor with absurd WR in micro volume. Six wins in seven says Evil Eye placement on the angle that matters; seven assists on two kills is pure intel value. Flex behind Thorn's one-fifty-three — not a default over the trap main."},
        ],
    },
    "mynameisblang": {
        "debrief": "<p><b>Platinum V · 3,048 RP · 73–69 · 51.3% win rate · 0.86 K/D.</b> Jun 23 four-game block: Bank 5:3 W, Kafe 4:1 with a 1v2 Clutch and 3K, Chalet and Oregon Ls. Jun 22 Oregon 5:3 with three 2K tags. Jun 21 Oregon 4:5 had a 4K and 3K that still couldn't close. Platinum V secured.</p><p><b>Finka at 50.0% over one hundred fourteen attack rounds</b>, <b>Oryx at 57.4% over ninety-four</b>, <b>Thunderbird at 59.1% over ninety-three</b> — three mains north of ninety rounds each.</p><p>Peak <b>3,142</b>. Fifty-two RP to Platinum IV. Ride Thunderbird and Oryx, time Finka boosts with stack executes, and stop letting Oregon overtime eat 4K decorations.</p>",
        "comments": [
            {"type": "map", "subject": "Bank", "date": "Jun 23", "text": "Jun 23 Bank 5:3 — five-eight-three, sixty percent headshots, Victim and two 2K tags on the W that parked you at 3,048 Platinum V. After Jun 22 Oregon and Jun 21's rollback noise, Bank was stack closure: trades that finish, plant timed, rank tier secured. Fifty-two RP to Platinum IV from here."},
            {"type": "operator", "subject": "Thunderbird", "date": "Jun 23", "text": "Ninety-three defensive rounds, 59.1% win rate, 1.26 K/D, thirty assists — Kóna sustain anchor at elite volume. Fifty-five wins in ninety-three says placement and rez timing print rounds; 55.8% headshots on seventy-seven kills says the Spear still frags. Queue her on denial sites when the stack needs a floor that doesn't fold."},
            {"type": "operator", "subject": "Oryx", "date": "Jun 23", "text": "Ninety-four defensive rounds, 57.4% win rate, 1.04 K/D, 73.3% headshots — roam anchor with real frag upside. Fifty-four wins in ninety-four says Remah Dash pressure on flanks that collapse late; seventy-five kills says the gun backs the mobility. Unconventional Oryx at fifty-seven percent WR — leave it alone, it's working."},
            {"type": "operator", "subject": "Finka", "date": "Jun 23", "text": "One hundred fourteen attack rounds, 50.0% win rate, 0.98 K/D, fifty-six percent headshots — boost operator at season volume. Fifty-seven wins in one-fourteen says break-even at scale; twenty-six assists on eighty-four kills says the team eats the advantage when you boost on commit. Time the adrenal surge with the plant, not the dry peek."},
            {"type": "operator", "subject": "Dokkaebi", "date": "Jun 23", "text": "Ninety-two attack rounds, 42.4% win rate, 0.62 K/D, eighteen assists — Jegeo Payload at grind volume with weak frags. Thirty-nine wins in ninety-two says intel pressure without enough closure; coach the habit: scan the anchor, hack on commit, don't hoard charges for cinematic rounds that never land."},
            {"type": "operator", "subject": "Doc", "date": "Jun 23", "text": "Twenty-five defensive rounds, 72.0% win rate, 2.33 K/D, sixty-four point three percent headshots — MP7 anchor in a smaller sample that screams when queued. Eighteen wins in twenty-five says stim sustain on the site angle; twenty-eight kills on twelve deaths is surgical, not spread. Flex behind Thunderbird's ninety-three — not a default over the volume anchors."},
        ],
    },
}

OVERSIGHT_WAVE = [
    {"type": "map", "subject": "Bank", "date": "Jun 23", "text": "Jun 23 Bank 5:3 was the squad's shared closure map — CunderThock and Mynameisblang both banked Ws the same night at 2,548 and 3,048 RP. Bank punishes teams that win mid-round duels but lose the post-plant; when multiple dossiers move on the same map block with matching scorelines, the lesson is stack round closure, not individual highlight reels. Gold V and Platinum V in the same lobby is the System Override receipt."},
    {"type": "operator", "subject": "Tachanka", "date": "Jun 23", "text": "CunderThock's Tachanka: one hundred eleven defensive rounds, 63.1% win rate — still the squad's highest-volume anchor after Bank closed Gold V. Grandmaster Sandman hit the same tier on Kaid and Sledge without queuing the Lord once. Two anchor philosophies, both printing; Rogue_Amputee and Matticus HQ still need a locked defensive main while the templates sit on adjacent dossiers."},
    {"type": "operator", "subject": "Aruni", "date": "Jun 21", "text": "slackandlack's Aruni: thirty-four rounds, 67.6% win rate, 1.92 K/D, two aces — Surya Gate denial with EBR frag upside on the Jun 21 Coastline heater. Cross-roster anchors split: Cunder on Tachanka, Sandman on Kaid/Frost, slack on Aruni/Doc. The stack's defensive chairs are filled; the leak is still attack-side closure on Chalet and Outback shutouts."},
    {"type": "operator", "subject": "Thorn", "date": "Jun 23", "text": "MJester1337's Thorn: one hundred fifty-three defensive rounds, 60.8% win rate, sixty-three assists — the grind anchor at one hundred eleven matches. Rogue's Thorn at thirteen rounds is the surgical call; MJester's is the career. Trap ops win on assists and plant denial — judge MJester's row on round impact, not the 0.84 season K/D."},
    {"type": "operator", "subject": "Thunderbird", "date": "Jun 23", "text": "Mynameisblang's Thunderbird: ninety-three defensive rounds, 59.1% win rate, 1.26 K/D — Platinum V anchor at volume. LceW4ll0wCome's Kaid at 82.4% over seventeen is the smurf receipt; Blang's Thunderbird is the main-account climb. Cross-squad lesson: denial anchors that rez and hold print rank when attack stops donating 0:4s."},
    {"type": "operator", "subject": "Sledge", "date": "Jun 20", "text": "Grandmaster Sandman's Sledge: sixty-one attack rounds, 52.5% win rate, 1.29 K/D — Gold V hammer at stack volume. CunderThock's Zero at ninety-five attack rounds and 45.3% is the cautionary spread tale on the same roster night. Sandman's consolidation arc is the squad memo: lock attack mains before game sixty, not after Calypso taxes rank."},
]


def apply_wave(slug, wave):
    path = ROOT / "data" / slug / "Y11S2" / "current.md"
    text = path.read_text(encoding="utf-8")
    m = re.search(r"```json\s*([\s\S]*?)```", text)
    data = json.loads(m.group(1))
    data["debrief"] = wave["debrief"]
    data["comments"] = wave["comments"] + data.get("comments", [])
    data["updated"] = UPDATED
    header = text.split("```json")[0]
    header = re.sub(r"\*\*Updated:\*\*.*", f"**Updated:** {UPDATED}", header)
    body = json.dumps(data, indent=4, ensure_ascii=False)
    path.write_text(f"{header}```json\n{body}\n```\n", encoding="utf-8")
    print(f"{slug}: debrief + {len(wave['comments'])} comments prepended to log")


def apply_oversight():
    path = ROOT / "data" / "oversight" / "Y11S2" / "current.md"
    text = path.read_text(encoding="utf-8")
    m = re.search(r"```json\s*([\s\S]*?)```", text)
    data = json.loads(m.group(1))
    data["comments"] = OVERSIGHT_WAVE + data.get("comments", [])
    data["updated"] = UPDATED
    header = text.split("```json")[0]
    header = re.sub(r"\*\*Updated:\*\*.*", f"**Updated:** {UPDATED}", header)
    body = json.dumps(data, indent=4, ensure_ascii=False)
    path.write_text(f"{header}```json\n{body}\n```\n", encoding="utf-8")
    print("oversight: wave appended")


if __name__ == "__main__":
    for slug, wave in WAVES.items():
        apply_wave(slug, wave)
    apply_oversight()
