#!/usr/bin/env python3
"""Append comment waves + refresh debriefs for Y11S2 Jun 28 bulk update."""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
UPDATED = "Jun 28, 2026 · evening PT"

WAVES = {
    "matticus_hq": {
        "debrief": "<p><b>Silver IV · 2,149 RP · 12–12 · 50.0% win rate · 0.86 K/D.</b> Jun 25–27 block split even — Oregon 4:0 W then twin Oregon donations including a 4K that still lost 2:4. Jun 26 Lair and Oregon printed; Consulate 2:4 Victim tax closed the night. Thirty-two RP off the 2,181 peak.</p><p><b>Skopós at 64.7% over thirty-four defensive rounds</b> anchors the cam shell; <b>Finka at 56.2% over sixteen attack rounds</b> at 1.67 K/D backs the boost. <b>Alibi at 66.7% over fifteen</b> holds the intel roamer receipt.</p><p>Peak <b>2,202</b> this stretch. Fifty-one RP to Silver III. Queue Skopós and Finka, stop decorating Oregon Ls with 4K tags that never plant, and log the stack before the data drifts again.</p>",
        "comments": [
            {"type": "map", "subject": "Oregon", "date": "Jun 27", "text": "Jun 27 Oregon 2:4 — six-four-two, sixty-six point seven percent headshots, a 4K and 1v3 Lost buried in the L that donated twenty-six RP. You had the highlight reel and not the round closure — Oregon punishes teams that win duels but lose the post-plant clock. Silver IV at 2,149 means the 4K tax is real rank, not decoration."},
            {"type": "operator", "subject": "Skopós", "date": "Jun 27", "text": "Thirty-four defensive rounds, 64.7% win rate, 0.57 K/D, nine assists — cam anchor at season volume doing the Y11S2 denial job. Twenty-two wins in thirty-four says the shell holds when phone discipline lands; weak K/D is expected on intel anchors when breaches get denied. Dismiss the hack, reposition the cams, let the team trade off your pings — not hero peek because the gun feels quiet."},
            {"type": "operator", "subject": "Finka", "date": "Jun 26", "text": "Sixteen attack rounds, 56.2% win rate, 1.67 K/D, sixty-six point seven percent headshots — boost operator printing when the stack commits. Fifteen kills on nine deaths says timed Adrenal Surge pushes, not ego peeks; four assists on fifteen kills says the team ate the advantage. Queue her on execute nights when Oregon and Lair need horsepower behind the plant."},
            {"type": "operator", "subject": "Alibi", "date": "Jun 26", "text": "Fifteen defensive rounds, 66.7% win rate, 1.00 K/D, three assists — Prisma decoys on real entry lines, ten wins in fifteen. Intel roamer value shows in pings that become trades; fifty-three point eight percent headshots on thirteen kills says MPX refrags land when decoys bait the shot. Spread decoys on approaches attackers shoot, then collect the reveal."},
            {"type": "operator", "subject": "Sens", "date": "Jun 25", "text": "Twelve attack rounds, 41.7% win rate, 1.00 K/D, five assists — XK23 flex with smoke and plant utility at modest volume. Five wins in twelve says secondary pick, not spread disease — coach the habit: smoke the choke that opens site, plant behind cover, don't dry peek because the gun felt fine on one map."},
            {"type": "operator", "subject": "Deimos", "date": "Jun 25", "text": "Eight attack rounds, 62.5% win rate, 1.67 K/D — Y11S2 attacker flex with positive signal in a real sample. Five wins in eight says duels land when queued intentionally on frag-leaning minutes. Don't dilute with one-round Ram and Pulse labs while Skopós and Finka carry the actual ranked minutes."},
        ],
    },
    "cunderthock": {
        "debrief": "<p><b>Gold V · 2,568 RP · 28–24 · 53.8% win rate · 0.96 K/D.</b> Jun 28 Chalet 4:0 with 4K and 2K parked you at 2,568 — twenty RP above the Jun 23 Bank close. Jun 27 twin Oregon Ls donated fifty-five; Jun 26 Lair 3K and Oregon 4:0 recovered. Jun 24 squad Emerald/Oregon/Consulate block logged.</p><p><b>Tachanka at 62.5% over one hundred thirty-six defensive rounds</b> is still the Lord's dossier. <b>Zero at 43.4% over one hundred twenty-two attack rounds</b> is the volume bleed to coach.</p><p>Peak <b>2,626</b>. Fifty-two RP to Gold IV. Queue the Lord first, run Zero for cams — not hero peeks — and stop letting Oregon overtime eat rank after Chalet already proved the read.</p>",
        "comments": [
            {"type": "map", "subject": "Chalet", "date": "Jun 28", "text": "Jun 28 Chalet 4:0 — six-one-one, fifty percent headshots, 4K and 2K on the shutout that banked twenty-five RP to 2,568. After Jun 27's twin Oregon donations and Jun 26's mixed block, Chalet was stack closure: trades that finish, plant timed, rank pushed past the Jun 23 Bank anchor. Fifty-two RP to Gold IV from here."},
            {"type": "operator", "subject": "Tachanka", "date": "Jun 28", "text": "One hundred thirty-six defensive rounds, 62.5% win rate, 0.94 K/D, forty-two assists — the Lord is still the spine of a Gold V dossier at 2,568 RP. Eighty-five wins in one-thirty-six says LMG denial scales when you commit; Jun 22's 4K on a 0:4 Chalet L proves frags without closure still tax rank. Anchor first, refrag second, hero ball never."},
            {"type": "operator", "subject": "Zero", "date": "Jun 27", "text": "One hundred twenty-two attack rounds, 43.4% win rate, 0.82 K/D, twenty-three assists — intel volume without enough round closure. Fifty-three wins in one-twenty-two says the cams are working; the execute isn't always following. Coach the habit: Argus on the breach that opens site, refrag with the team — not solo peek because fifty-two percent headshots look fine on paper."},
            {"type": "operator", "subject": "Twitch", "date": "Jun 26", "text": "Nine attack rounds, 66.7% win rate, 3.50 K/D, fifty percent headshots — F2 lab that actually closed in a small sample. Six wins in nine says purposeful duelist minutes when the stack syncs; fourteen kills on four deaths is loud frag signal. Flex behind Tachanka defense when the site needs hard breach denial clear — not default over Zero volume."},
            {"type": "operator", "subject": "Jackal", "date": "Jun 24", "text": "Seven attack rounds, 42.9% win rate, 2.75 K/D, 63.6% headshots — tiny sample, loud frag signal on the Jun 24 Oregon 5:3 W. Footprint tracking when the stack syncs; three wins in seven says don't default over Zero's one-twenty-two, but ride him when the map needs hard trades after Emerald donates."},
            {"type": "operator", "subject": "Bandit", "date": "Jun 24", "text": "Twelve defensive rounds, 66.7% win rate, 0.45 K/D, five assists — trick anchor printing in a modest sample. Eight wins in twelve says active tricking when queued intentionally; low K/D is fine on Bandit when the wall denies the hard breach. Stack with Tachanka on denial sites — Electroclaw overlap without spreading into Snake's nine percent WR lab."},
        ],
    },
    "rogue_amputee": {
        "debrief": "<p><b>Bronze II · 1,856 RP · 25–30 · 45.5% win rate · 0.97 K/D.</b> Jun 28 Consulate 4:2 W clawed one RP back after a 1 W 3 L block. Jun 27 Chalet 1v3 Clutch 3K in a 2:4 L is the highlight tax. Jun 25 five-game heater — Chalet and Nighthaven shutouts plus Clubhouse 2K. Jun 24 squad block logged.</p><p><b>Mute at 47.8% over sixty-nine defensive rounds</b> still leads volume; <b>Nomad at 52.5% over sixty-one attack rounds</b> at 1.10 K/D is the disciplined line. <b>Kaid at 62.2% over thirty-seven</b> keeps the anchor receipt printing.</p><p>Peak <b>1,951</b>. Forty-four RP to Bronze I. Stack Kaid with Mute, ride Nomad beside Dokkaebi, and stop letting Jun 28 Oregon 4:5 3K decorations undo Chalet closure.</p>",
        "comments": [
            {"type": "map", "subject": "Chalet", "date": "Jun 27", "text": "Jun 27 Chalet 2:4 — six-three-zero, sixteen point seven percent headshots, 1v3 Clutch and 3K buried in the L that donated twenty-four RP. You had the clutch highlight and not the round closure — Chalet punishes teams that win mid-round duels but lose the plant clock. Bronze II at 1,856 means the 3K tax is real rank, not a consolation badge."},
            {"type": "operator", "subject": "Mute", "date": "Jun 28", "text": "Sixty-nine defensive rounds, 47.8% win rate, 0.77 K/D, seventeen assists — still the volume leader and still treading water. Jammers on the breach wall the attack actually needs, drone denial in prep, overlap with Kaid so Thatcher spends twice. Sub-fifty on sixty-nine rounds is placement discipline, not aim — fix the wall before you fix the gun."},
            {"type": "operator", "subject": "Nomad", "date": "Jun 25", "text": "Sixty-one attack rounds, 52.5% win rate, 1.10 K/D, sixteen assists — still the disciplined line beside Dokkaebi. Thirty-two wins in sixty-one is break-even volume done right; Airjabs seal the flank the roamers use to collapse your execute. Jun 25 Nighthaven and Chalet Ws had impact tags — Nomad's job is map control first, highlight ball second."},
            {"type": "operator", "subject": "Kaid", "date": "Jun 25", "text": "Thirty-seven defensive rounds, 62.2% win rate, 1.04 K/D, twelve assists — the claws still print when Mute treads water. Twenty-three wins in thirty-seven says the anchor habit holds; Electroclaws on the breach wall and hatch that gate the hard push. Stack with Mute on Chalet and Nighthaven nights so denial actually sticks."},
            {"type": "operator", "subject": "Dokkaebi", "date": "Jun 26", "text": "Twenty-six attack rounds, 46.2% win rate, 1.06 K/D, twelve assists — Jegeo Payload still converting at volume. Twelve assists on eighteen kills says the remaster is team work; scan, hack, force phone discipline, collect the refrag. Stay parked beside Nomad — Gridlock at 26.3% isn't competing for this slot."},
            {"type": "operator", "subject": "Thorn", "date": "Jun 26", "text": "Sixteen defensive rounds, 50.0% win rate, 1.40 K/D, seven assists — trap anchor with frag upside in a growing sample. Eight wins in sixteen says Razorblooms on the plant window when queued intentionally; thirty-five point seven percent headshots on fourteen kills says the gun backs the traps. Flex behind Mute volume — not a default over Kaid when the claws are printing at sixty-two percent."},
        ],
    },
    "grandmaster_sandman": {
        "debrief": "<p><b>Gold V · 2,548 RP · 32–29 · 52.5% win rate · 1.18 K/D.</b> Jun 28 five-game block: Consulate 4K 1v1 Clutch W, Chalet 4:0, twin Oregon taxes. Jun 24–27 catch-up after Jun 20 dormancy — Emerald squad block through Lair 4:1 and Oregon 4:0. Largest RP swing since the squad marathon.</p><p><b>Sledge at 51.3% over seventy-six attack rounds</b> at 1.28 K/D leads the hammer. <b>Kaid at 66.7% over thirty-three defensive rounds</b> and <b>Frost at 71.0% over thirty-one</b> hold the anchor row. <b>Denari at 92.3% over thirteen</b> is the perfect micro sample.</p><p>Peak <b>2,677</b>. Fifty-two RP to Gold IV. Queue Kaid, Frost, and Sledge — not another Oregon 4:5 Ace that prints highlights and donates the ticket.</p>",
        "comments": [
            {"type": "map", "subject": "Consulate", "date": "Jun 28", "text": "Jun 28 Consulate 4:2 — twelve-two-zero, forty-one point seven percent headshots, 4K and 1v1 Clutch on the W that banked twenty-three RP. After Jun 27's twin Oregon donations, Consulate was the stack-closure read: frag volume that actually closed the set on the map the squad converged on. Gold V at 2,548 — hammer timing plus clutch discipline, not solo hero ball."},
            {"type": "operator", "subject": "Sledge", "date": "Jun 28", "text": "Seventy-six attack rounds, 51.3% win rate, 1.28 K/D, twenty-three assists — the hammer leads volume at Gold V after the Jun 24–28 catch-up. Thirty-nine wins in seventy-six says purposeful entries, not nostalgia rushes; 38.5% headshots on seventy-eight kills says aim backs the plant clock. Queue him when the breach wall is soft and the stack commits to closure."},
            {"type": "operator", "subject": "Kaid", "date": "Jun 26", "text": "Thirty-three defensive rounds, 66.7% win rate, 1.14 K/D, seven assists — Electroclaw anchor printing beside Frost. Twenty-two wins in thirty-three says denial over highlight frags; claws on the breach wall that gates the hard push. Stack with Frost on denial sites — the squad's defensive gold standard after Jun 20 dormancy ended."},
            {"type": "operator", "subject": "Frost", "date": "Jun 26", "text": "Thirty-one defensive rounds, 71.0% win rate, 1.20 K/D, twelve assists — trap mat anchor at elite WR. Twenty-two wins in thirty-one says welcome mats on the approach attackers walk; twelve assists on twenty-four kills says traps bought trades the sheet loves. Pair with Kaid on Oregon and Lair nights when denial needs to stick."},
            {"type": "operator", "subject": "Thorn", "date": "Jun 26", "text": "Twenty-six defensive rounds, 50.0% win rate, 1.45 K/D, twelve assists — trap anchor with frag upside at even split. Twenty-nine kills on twenty deaths says Razorblooms punish when placed on the plant window; one ace says the ceiling is there. Bloom the real approach, hold the angle that collects — not spread over Kaid's sixty-six point seven percent line."},
            {"type": "operator", "subject": "Denari", "date": "Jun 28", "text": "Thirteen defensive rounds, 92.3% win rate, 2.40 K/D, seven assists — perfect sample, loud signal on the Y11S2 defender. Twelve wins in thirteen says when you queue Denari, the gadget lands; 41.7% headshots on twelve kills says surgical minutes. Protect these picks — not another operator spread night while Sledge grinds seventy-six rounds."},
        ],
    },
    "slackandlack": {
        "debrief": "<p><b>Silver II · 2,327 RP · 27–24 · 52.9% win rate · 1.17 K/D.</b> Jun 28 five-game block: Chalet 4:0 2K and Consulate 4K W, then Oregon and Bank taxes. Jun 27 Chalet split 1 W 1 L. Jun 21 Coastline heater still anchors the season high at 2,377.</p><p><b>Osa at 44.9% over forty-nine attack rounds</b> at 1.42 K/D leads attack volume. <b>Doc at 58.3% over forty-eight defensive rounds</b> anchors. <b>Aruni at 70.0% over forty</b> at 1.74 K/D is the EBR receipt.</p><p>Peak <b>2,377</b>. Seventy-three RP to Silver I. Ride Aruni and Doc, time Osa pushes with the stack, and stop donating Jun 28 Bank 3:5 after Chalet already printed.</p>",
        "comments": [
            {"type": "map", "subject": "Chalet", "date": "Jun 28", "text": "Jun 28 Chalet 4:0 — five-two-one, eighty percent headshots, 2K on the shutout that banked twenty-six RP at 2,327. Squad stack night symmetry with Cunder, Sandman, and MJester on the same map block — clean closure after Consulate and Oregon taxes in the same session. Chalet rewards stack trades on site; you brought the gate and the gun."},
            {"type": "operator", "subject": "Osa", "date": "Jun 28", "text": "Forty-nine attack rounds, 44.9% win rate, 1.42 K/D, sixty-one point one percent headshots — T-5 shield and plant pressure at volume. Twenty-two wins in forty-nine says the attack spread needs closure discipline; one ace says the ceiling is there when pushes sync. Coach the habit: shield the planter on Consulate 4K nights, not the solo peek that donates Bank."},
            {"type": "operator", "subject": "Doc", "date": "Jun 28", "text": "Forty-eight defensive rounds, 58.3% win rate, 1.12 K/D, sixty-two point two percent headshots — MP7 anchor with stim sustain. Forty-five kills on forty deaths, twenty-eight wins in forty-eight — highest defensive volume and above break-even. Hold the site angle, stim the trade, don't ego peek off the anchor role when Aruni is posting seventy percent."},
            {"type": "operator", "subject": "Aruni", "date": "Jun 28", "text": "Forty defensive rounds, 70.0% win rate, 1.74 K/D, two aces — Surya Gate anchor with real EBR frag upside. Fifty-four kills on thirty-one deaths says aggressive angle holding is working; twenty-eight wins in forty says gates on the entries attackers must cross. Queue her when the site needs denial and duels on Chalet stack nights."},
            {"type": "operator", "subject": "Thermite", "date": "Jun 27", "text": "Twenty-four attack rounds, 41.7% win rate, 1.05 K/D, forty-five percent headshots — hard breach flex when the wall matters. Ten wins in twenty-four says situational value over default; pair with Thatcher clear on ranked breach walls. Not every site needs Thermite — queue when the reinforced wall is the win condition, not spread over Osa's forty-nine."},
            {"type": "operator", "subject": "Smoke", "date": "Jun 27", "text": "Sixteen defensive rounds, 50.0% win rate, 1.00 K/D, four assists — toxic bar anchor at even split. Thirteen kills on thirteen deaths says round impact when smokes land on the choke; fifty-three point eight percent headshots says the M590 backs the deny. Flex behind Doc and Aruni volume — not a default over the denial chairs that print at fifty-eight and seventy percent."},
        ],
    },
    "mjester1337": {
        "debrief": "<p><b>Bronze II · 1,813 RP · 73–63 · 53.7% win rate · 0.87 K/D.</b> Jun 28 eight-game marathon promoted you to Bronze II — Border 4:1 4K, Chalet 4:0, Calypso split. Jun 27 sixteen-game block with Kafe 3K TK W. One hundred thirty-six ranked matches — the grind anchor season.</p><p><b>Thorn at 61.7% over one hundred eighty-eight defensive rounds</b> is the spine. <b>Denari at 53.6% over one hundred twelve</b> and <b>Dokkaebi at 45.6% over sixty-eight</b> split duty.</p><p>Peak <b>1,813</b> — new tier. Eighty-seven RP to Bronze I. Queue Thorn, ride the Border 4K receipt, and stop letting Jun 28 Oregon Victim donations undo an eight-game promotion night.</p>",
        "comments": [
            {"type": "map", "subject": "Border", "date": "Jun 28", "text": "Jun 28 Border 4:1 — seven-one-one, twenty-eight point six percent headshots, 4K on the W that banked twenty-six RP in the eight-game marathon. After Jun 27's sixteen-game block and Calypso taxes, Border was closure: multi-kill impact that actually closed the set and pushed you into Bronze II at 1,813. Vertical reads plus plant discipline — not another highlight reel on a loss."},
            {"type": "operator", "subject": "Thorn", "date": "Jun 28", "text": "One hundred eighty-eight defensive rounds, 61.7% win rate, 1.32 K/D, seventy-three assists — the season's spine at one hundred thirty-six matches and Bronze II. One hundred sixteen wins in one-eighty-eight says Razorblooms on the plant window or choke the attack walks; one ace says the ceiling still climbs. Queue her first on defense — not another Montagne spread night at sixty-two rounds."},
            {"type": "operator", "subject": "Denari", "date": "Jun 28", "text": "One hundred twelve defensive rounds, 53.6% win rate, 0.57 K/D, thirty-six assists — Y11S2 defender at volume with team impact over frags. Sixty wins in one-twelve says the gadget is doing work even when K/D looks thin; sixty-six point seven percent headshots on fifty-one kills says precision traps. Anchor-trap op — judge denial and assists, not highlight K/D."},
            {"type": "operator", "subject": "Dokkaebi", "date": "Jun 27", "text": "Sixty-eight attack rounds, 45.6% win rate, 0.88 K/D, twenty-four assists — Jegeo Payload at grind volume. Thirty-one wins in sixty-eight says the hack converts when the stack syncs; twenty-four assists says phone pressure is team value. Stay on her for attack defaults over Gridlock at 52.5% with weaker round impact."},
            {"type": "operator", "subject": "Montagne", "date": "Jun 27", "text": "Sixty-two defensive rounds, 48.4% win rate, 0.34 K/D — shield anchor at volume with sub-fifty WR. Thirty wins in sixty-two says the extendo still buys time when the stack trades; three assists on fourteen kills is pure denial value. Not a frag op — coach the habit: hold the choke the plant needs, don't rotate for hero peeks when Thorn is posting sixty-one point seven percent."},
            {"type": "operator", "subject": "Lion", "date": "Jun 27", "text": "Forty-three attack rounds, 53.5% win rate, 0.81 K/D, eight assists — EE-One-D flex with two TKs logged. Twenty-three wins in forty-three says intel pressure when the execute follows; forty-eight percent headshots on twenty-five kills says the V308 converts on commit. Surgical attack pick behind Dokkaebi volume — not spread over Thorn's one-eighty-eight defensive minutes."},
        ],
    },
    "lcew4ll0wcome": {
        "debrief": "<p><b>Silver IV · 2,156 RP · 13–15 · 48.1% win rate · 1.20 K/D.</b> Jun 24 Oregon 1:4 — six-four-one, twin 2K tags and double 1v3 Lost buried in a twenty-six RP donation. Smurf idle since Jun 21 Outback heater; one ranked game logged this block.</p><p><b>Kaid at 77.8% over eighteen defensive rounds</b> at 3.50 K/D is still absurd anchor math. <b>Valkyrie at 68.8% over sixteen</b> and <b>Kapkan at 70.0% over ten</b> back the denial row. <b>Nomad at 34.6% over twenty-six</b> is the attack tax.</p><p>Peak <b>2,191</b>. Forty-four RP to Silver III. Queue Kaid and Valkyrie on defense, treat the alt like a rank push — not a highlight reel audition on Oregon 1:4 nights.</p>",
        "comments": [
            {"type": "map", "subject": "Oregon", "date": "Jun 24", "text": "Jun 24 Oregon 1:4 — six-four-one, sixteen point seven percent headshots, twin 2K tags and double 1v3 Lost buried in the shutout that donated twenty-six RP. Squad Emerald block same night — you had the multi-kill impact and not the round closure. Silver IV at 2,156 means the smurf tax is real; Rogue's main dossier is chasing the same Kaid template you're already posting at seventy-seven point eight percent."},
            {"type": "operator", "subject": "Kaid", "date": "Jun 24", "text": "Eighteen defensive rounds, 77.8% win rate, 3.50 K/D, seven assists — the smurf's anchor receipt still absurd. Fourteen wins in eighteen says Electroclaws on the wall that gates the real push; twenty-one kills on six deaths is denial over highlight frags. This is the template Rogue's main dossier keeps chasing — protect these minutes, don't dilute with Nomad spread on defense."},
            {"type": "operator", "subject": "Jackal", "date": "Jun 24", "text": "Thirty attack rounds, 36.7% win rate, 1.05 K/D, 54.5% headshots — highest attack volume on the alt and still below break-even. Eleven wins in thirty says the gun is fine, the plant clock isn't. Coach the habit: ping, trade, plant — not ping, peek, donate on Oregon nights when Kaid is posting 3.50 K/D on the other side."},
            {"type": "operator", "subject": "Nomad", "date": "Jun 24", "text": "Twenty-six attack rounds, 34.6% win rate, 0.95 K/D, four assists — Airjabs without round closure is the tax. Nine wins in twenty-six says the flex isn't earning queue time over Jackal when Kaid is posting 77.8% on defense. Nomad wins when traps slow the push the team punishes — not solo flank hero ball on a smurf still grinding Silver."},
            {"type": "operator", "subject": "Valkyrie", "date": "Jun 21", "text": "Sixteen defensive rounds, 68.8% win rate, 1.86 K/D, five assists — Black Eye intel buying trades the sheet loves. Eleven wins in sixteen says the alt's defensive ceiling still lives here. Cam coverage on flanks, active callouts, MPX refrags — queue her first on stack defense nights beside Kaid."},
            {"type": "operator", "subject": "Kapkan", "date": "Jun 21", "text": "Ten defensive rounds, 70.0% win rate, 1.60 K/D, eight assists — trap anchor printing on a real sample. Seven wins in ten says traps on the approach attackers actually walk; eight assists on eight kills says placement discipline. Flex behind Kaid when the site needs denial, not Jackal volume on the other side at thirty-six point seven percent."},
        ],
    },
}

OVERSIGHT_WAVE = [
    {"type": "map", "subject": "Chalet", "date": "Jun 28", "text": "Jun 28 Chalet was the squad's shared stack map — CunderThock 4:0 with 4K and 2K, Grandmaster Sandman 4:0, slackandlack 4:0 with 2K, MJester1337 4:0 with 2K, Rogue_Amputee 4:1 with 1v1 Clutch. Five dossiers, same map block, four shutouts and a narrow W. When the stack converges on Chalet and closes, the board moves — Gold V pushes to 2,568, Sandman holds 2,548, slack climbs to 2,327, MJester promotes to Bronze II. Oregon and Consulate in the same session still tax rank; Chalet was the closure receipt."},
    {"type": "operator", "subject": "Sledge", "date": "Jun 28", "text": "Grandmaster Sandman's Sledge: seventy-six attack rounds, 51.3% win rate, 1.28 K/D — Gold V hammer after Jun 24–28 catch-up ended the Jun 20 dormancy. Consulate 4K 1v1 Clutch Jun 28 is the stack's loudest attack receipt. CunderThock's Zero at one-twenty-two rounds and 43.4% is the cautionary intel spread on the same roster night. Sandman's consolidation arc is still the squad memo: lock attack mains before game seventy, not after Oregon donates."},
    {"type": "operator", "subject": "Thorn", "date": "Jun 28", "text": "MJester1337's Thorn: one hundred eighty-eight defensive rounds, 61.7% win rate, seventy-three assists — Bronze II at 1,813 after Border 4K and Chalet 4:0 in an eight-game Jun 28 marathon. One hundred thirty-six ranked matches — the grind anchor promoted while the K/D sheet still reads 0.87. Rogue's Thorn at sixteen rounds is the surgical call; MJester's is the career. Trap ops win on assists and plant denial — judge the row on round impact."},
    {"type": "operator", "subject": "Skopós", "date": "Jun 27", "text": "Matticus HQ's Skopós: thirty-four defensive rounds, 64.7% win rate — cam anchor at season volume while Oregon 4K still lost 2:4 Jun 27. Finka at 56.2% over sixteen backs the attack chair for the first time at fifty-fifty record. Cross-roster contrast: Cunder on Tachanka one-thirty-six, Sandman on Kaid thirty-three at 66.7%, slack on Aruni forty at 70.0%. Matticus finally has both chairs — the leak is still highlight ball without plant closure on Oregon."},
    {"type": "operator", "subject": "Mute", "date": "Jun 28", "text": "Rogue_Amputee's Mute: sixty-nine defensive rounds, 47.8% win rate, seventeen assists — volume leader still treading water at Bronze II 1,856 RP despite Jun 25 Chalet and Nighthaven heater. Nomad at 52.5% over sixty-one is the attack line printing beside Dokkaebi. Cross-roster lesson: Kaid at 62.2% over thirty-seven says the claws work when stacked with Mute — fix the jammer wall before you fix the gun on a 1 W 3 L Jun 28 block."},
    {"type": "operator", "subject": "Aruni", "date": "Jun 28", "text": "slackandlack's Aruni: forty defensive rounds, 70.0% win rate, 1.74 K/D, two aces — gate anchor at Silver II 2,327 after Jun 28 Chalet 4:0. Doc at 58.3% over forty-eight and Osa at 44.9% over forty-nine split the other chairs. Cross-roster anchors: Cunder on Tachanka, Sandman on Kaid/Frost, MJester on Thorn. slack's defensive identity is locked — the tax is still Osa attack closure and Bank 3:5 donations after Chalet prints."},
]


def apply_wave(slug, wave):
    path = ROOT / "data" / slug / "Y11S2" / "current.md"
    text = path.read_text(encoding="utf-8")
    m = re.search(r"```json\s*([\s\S]*?)```", text)
    data = json.loads(m.group(1))
    data["debrief"] = wave["debrief"]
    data["comments"] = data.get("comments", []) + wave["comments"]
    data["updated"] = UPDATED
    header = text.split("```json")[0]
    header = re.sub(r"\*\*Updated:\*\*.*", f"**Updated:** {UPDATED}", header)
    body = json.dumps(data, indent=4, ensure_ascii=False)
    path.write_text(f"{header}```json\n{body}\n```\n", encoding="utf-8")
    print(f"{slug}: debrief + {len(wave['comments'])} comments appended (latest wave)")


def apply_oversight():
    path = ROOT / "data" / "oversight" / "Y11S2" / "current.md"
    text = path.read_text(encoding="utf-8")
    m = re.search(r"```json\s*([\s\S]*?)```", text)
    data = json.loads(m.group(1))
    data["comments"] = data.get("comments", []) + OVERSIGHT_WAVE
    data["updated"] = UPDATED
    header = text.split("```json")[0]
    header = re.sub(r"\*\*Updated:\*\*.*", f"**Updated:** {UPDATED}", header)
    body = json.dumps(data, indent=4, ensure_ascii=False)
    path.write_text(f"{header}```json\n{body}\n```\n", encoding="utf-8")
    print("oversight: wave 11 appended")


if __name__ == "__main__":
    for slug, wave in WAVES.items():
        apply_wave(slug, wave)
    apply_oversight()
